name: Scrape latest Ft Myers st. data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '*/30 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl https://api.tidesandcurrents.noaa.gov/api/prod/datagetter?begin_date=20220920%2010:00&end_date=20221010%2010:24&station=8725520&product=water_level&datum=mtl&units=english&time_zone=gmt&application=web_services&format=csv > 8725520.csv
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
